# syntax=docker/dockerfile:1.0.0-experimental

FROM game-randomizer-dependency

RUN apt-get update -qq && apt-get install --no-install-recommends -y vim

RUN set -ex ;\
    if [ ${root:-0} -ne 0 ] && [ ${root:-0} -ne 0 ]; then \
        mkdir /home/cloudshell-user/.ssh; \
        ssh-keyscan github.com >> /home/cloudshell-user/.ssh/known_hosts; \
        chown -R root:root /home/cloudshell-user/.ssh; \
    fi;

WORKDIR /app
